name: workflow-on-issue-comment-event
on: issue_comment
# https://docs.github.com/ko/actions/reference/workflows-and-actions/events-that-trigger-workflows#issue_comment
# type 이 없는 기본 값으로는 모든 타입(created, edited, deleted)이 활성화 된다. 이 예시에서는 issue 가 생성될때만 실행되도록 함.
# default 브랜치에 이 파일이 존재해야 동작됨. (issue_comment event 는 브랜치와 무관한 repository event 라서..)
# issue comment 뿐만아니라 pull request comment 에서도 트리거 된다.

jobs:
  my-job-for-pull-request-comment:
    if: ${{ github.event.issue.pull_request }} # 긍정
    runs-on: ubuntu-latest
    steps:
      - name: my-step-for-pull-request-comment
        run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
  my-job-for-issue-comment:
    if: ${{ !github.event.issue.pull_request }} # 부정
    runs-on: ubuntu-latest
    steps:
      - name: my-step-for-issue-comment
        run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}