name: workflow-on-pull-request-event
on: pull_request # pull_request event 는 기본적으로 pull request 상태가 opened, synchronize, reopened 일 때 트리거 된다.
# https://docs.github.com/ko/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request

jobs:
  my-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-1
        run: echo hello github action
      - name: my-step-2
        run: |
          echo this is my-step-2
          echo good
